import type { Provider } from './providers/types.js';
import type { TriageItem } from './triage.js';
import type { UsageInfo } from './providers/types.js';

export interface BriefingInput {
  prTitle: string;
  prDescription: string;
  diff: string;
  changedFiles: string[];
  triageItems: TriageItem[];
}

export interface Briefing {
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH';
  whatChanged: string[];
  focusAreas: Array<{ file: string; reason: string }>;
  safeToSkip: string[];
  estimatedMinutes: number;
  usage?: UsageInfo;
}

const BRIEFING_PROMPT = `You are a PR navigator. Your ONLY job is to help a human reviewer orient themselves quickly. Do NOT review code quality — that is handled separately.

Output a single JSON object (no prose around it):
{
  "riskLevel": "LOW" | "MEDIUM" | "HIGH",
  "whatChanged": ["3-5 bullet points in plain English describing what this PR does"],
  "focusAreas": [{"file": "path/to/file", "reason": "why to spend time here"}],
  "safeToSkip": ["file or directory and why it is safe to skim"],
  "estimatedMinutes": 15
}

Risk rubric:
- HIGH: security-sensitive paths, core business logic, DB migrations, public API changes, auth
- MEDIUM: moderate logic changes, internal API changes, non-trivial refactors
- LOW: config tweaks, docs, minor additions, test-only changes, dependency bumps

estimatedMinutes: total changed lines / 50, floored at 5, capped at 90.
focusAreas: list only files worth a close read (deep-triaged, high-change-count, or security-relevant).
safeToSkip: lockfiles, generated code, trivial test additions, config-only changes.`;

export async function generateBriefing(
  provider: Provider,
  input: BriefingInput,
): Promise<Briefing> {
  const filesList = input.changedFiles.map((f) => `- ${f}`).join('\n');
  const triageSummary = input.triageItems
    .map((t) => `${t.path}: ${t.decision}${t.reason ? ` (${t.reason})` : ''}`)
    .join('\n');

  const totalLines = (input.diff.match(/^[+-]/gm) ?? []).length;
  const estimatedMinutes = Math.min(90, Math.max(5, Math.round(totalLines / 50)));

  const userBody = `PR Title: ${input.prTitle}
PR Description: ${input.prDescription || '(none)'}

Changed files:
${filesList}

Triage decisions:
${triageSummary}

Estimated changed lines: ${totalLines}
Suggested estimatedMinutes: ${estimatedMinutes}

Return ONLY the JSON object.`;

  const prompt = `${BRIEFING_PROMPT}\n\n${userBody}`;

  // ReviewInput requires: prTitle, prDescription, diff, changedFiles (FileContext[]), skills, prompt
  const result = await provider.review(
    {
      prompt,
      diff: '',
      changedFiles: input.changedFiles.map((f) => ({ path: f })),
      prTitle: input.prTitle,
      prDescription: input.prDescription,
      skills: '',
    },
    {},
  );

  // parse the raw response as JSON
  let parsed: any = {};
  try {
    const raw = result.rawResponse ?? '';
    const fence = raw.match(/```json\s*([\s\S]*?)```/);
    const candidate = fence ? fence[1] : raw;
    const start = candidate.indexOf('{');
    const end = candidate.lastIndexOf('}');
    if (start !== -1 && end !== -1) parsed = JSON.parse(candidate.slice(start, end + 1));
  } catch { /* use defaults */ }

  return {
    riskLevel: (['LOW', 'MEDIUM', 'HIGH'].includes(parsed.riskLevel) ? parsed.riskLevel : 'MEDIUM') as Briefing['riskLevel'],
    whatChanged: Array.isArray(parsed.whatChanged) ? parsed.whatChanged : [],
    focusAreas: Array.isArray(parsed.focusAreas) ? parsed.focusAreas : [],
    safeToSkip: Array.isArray(parsed.safeToSkip) ? parsed.safeToSkip : [],
    estimatedMinutes: typeof parsed.estimatedMinutes === 'number' ? parsed.estimatedMinutes : estimatedMinutes,
    usage: result.usage,
  };
}

export function formatBriefingMarkdown(briefing: Briefing, prTitle: string): string {
  const riskEmoji = { LOW: '🟢', MEDIUM: '🟡', HIGH: '🔴' }[briefing.riskLevel];
  const lines: string[] = [
    `## 🔍 Reviewer Briefing — ${prTitle}`,
    '',
    `**Risk:** ${riskEmoji} ${briefing.riskLevel} &nbsp;|&nbsp; **Estimated review time:** ~${briefing.estimatedMinutes} min`,
    '',
    '### What changed',
    ...briefing.whatChanged.map((b) => `- ${b}`),
  ];

  if (briefing.focusAreas.length > 0) {
    lines.push('', '### Focus here');
    for (const f of briefing.focusAreas) lines.push(`- **${f.file}** — ${f.reason}`);
  }

  if (briefing.safeToSkip.length > 0) {
    lines.push('', '### Safe to skim');
    for (const s of briefing.safeToSkip) lines.push(`- ${s}`);
  }

  lines.push('', '---', '*Generated by [lens](https://github.com/mintoak/lens) — local AI review assistant*');
  return lines.join('\n');
}
